### PR TITLE
virtual provides for php72u-yaml

### PR DESCRIPTION
**Pull request by Zodzie**
Let me know if any issues here! Thanks for the opportunity/thought in participating in hacktoberfest!

### CODE REVIEW

**Review by carlwgeorge — CHANGES_REQUESTED** [review]
This change looks good, and the build passes.  Can you also increase the Release by 1 and add a changelog entry?

**Comment by Zodzie** [comment]
@carlwgeorge  sorry I dropped the ball on this. Can you advise on how to 
increase the Release by 1 and add a changelog entry

**Comment by carlwgeorge** [comment]
`Version` corresponds to the upstream version in PECL, but `Release` is the version of the spec file for that upstream version.  It's normally reset to 1 with every new upstream version, but if you make changes to the spec file with the same upstream version you must increment the release so that yum sees it as an upgrade.

https://rpm-packaging-guide.github.io/#preamble-items

That should look like this:

```diff
 Version:        2.0.4
-Release:        1%{?dist}
+Release:        2%{?dist}
 Summary:        Support for YAML 1.1 serialization using the LibYAML library
```

The changelog describes the packaging changes.  Your entry will look similar to the other entries in the changelog, with an updated date, name, email, and version-release.  Something like this:

```diff
 %changelog
+* Mon Nov 18 2019 Ryan Rosado <ryan.rosado@bbthr.com> - 2.0.4-2
+- Add virtual provides for php72u-yaml

 * Mon Jun 10 2019 Carl George <carl@george.computer> - 2.0.4-1
 - Latest upstream
 - Build with pear1 instead of pear1u
```

**Comment by carlwgeorge** [comment]
[All php72u packages have been retired.](https://github.com/iusrepo/announce/issues/25)

**Pull request closed without merging**
